# Generated by Django 4.0 on 2022-11-18 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tatto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tattoo_artist',
            name='like',
            field=models.IntegerField(max_length=150),
        ),
    ]
