# Generated by Django 4.0 on 2022-11-21 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tatto', '0002_alter_tattoo_artist_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tattoo_artist',
            name='like',
            field=models.IntegerField(),
        ),
    ]
