# Generated by Django 4.0 on 2022-11-18 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='portafolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img1', models.TextField(max_length=150)),
                ('img2', models.TextField(max_length=150)),
                ('img3', models.TextField(max_length=150)),
                ('img4', models.TextField(max_length=150)),
                ('img5', models.TextField(max_length=150)),
                ('portafolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portafolio', to='accounts.users')),
            ],
        ),
    ]
