# Generated by Django 4.0 on 2022-11-21 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tattoDis', '0002_alter_disponibilidadmodel_dispo'),
    ]

    operations = [
        migrations.AddField(
            model_name='disponibilidadmodel',
            name='like',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='disponibilidadmodel',
            name='dispo',
            field=models.BooleanField(),
        ),
    ]
