# Generated by Django 3.2.9 on 2022-09-20 00:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tatoo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrousuarios',
            name='genero',
            field=models.CharField(choices=[('M', 'masculino'), ('F', 'femenino'), ('I', 'indefinido')], default='I', max_length=1),
        ),
        migrations.AlterField(
            model_name='portafolio_tatuadores',
            name='fecha_publicacion',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 19, 19, 6, 11, 456795)),
        ),
        migrations.AlterField(
            model_name='registrotatuadores',
            name='genero',
            field=models.CharField(choices=[('M', 'masculino'), ('F', 'femenino'), ('I', 'indefinido')], default='I', max_length=1),
        ),
    ]
