# Generated by Django 3.2.9 on 2022-10-12 15:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tatoo', '0002_auto_20220919_1906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrotatuadores',
            name='fecha_nacimiento',
        ),
        migrations.RemoveField(
            model_name='registrotatuadores',
            name='genero',
        ),
        migrations.RemoveField(
            model_name='registrousuarios',
            name='fecha_nacimiento',
        ),
        migrations.RemoveField(
            model_name='registrousuarios',
            name='genero',
        ),
        migrations.AlterField(
            model_name='portafolio_tatuadores',
            name='fecha_publicacion',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 12, 10, 41, 58, 720956)),
        ),
    ]
