# Generated by Django 4.0 on 2022-11-28 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotes',
            name='description',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='quotes',
            name='img',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='quotes',
            name='isActive',
            field=models.BooleanField(),
        ),
    ]
