# Generated by Django 4.0 on 2022-11-29 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0003_quotes_username_quotes_usertatto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotes',
            name='isActive',
            field=models.CharField(max_length=150),
        ),
    ]
